GET http://localhost:7070/kurious/instructor
###
GET http://localhost:7070/kurious/instructor/college/5efdd646752e750798e84888
###
GET http://localhost:7070/kurious/instructor/5efeffcff6e69021ecde08c4
###
POST http://localhost:7070/kurious/instructor
Content-Type: application/json

{
    "surName": "Nadine",
    "otherNames": "Umukura",
    "nationalId": "1103473948628496",
    "gender": "FeMale",
    "phone": "9999000000",
    "email": "umukura@gmail.com",
    "college": "5efdd646752e750798e84888"
}

###
PUT http://localhost:7070/kurious/instructor/5efeffcff6e69021ecde08c4
Content-Type: application/json

{
    "surName": "Nadina",
    "otherNames": "Umukura",
    "nationalId": "1103473948628496",
    "gender": "FeMale",
    "phone": "9999000000",
    "email": "umukura@gmail.com",
    "college": "5efdd646752e750798e84888"
}

###
POST http://localhost:7070/kurious/instructor/login
Content-Type: application/json

{
    "password": "Kurious@2020",
    "email": "umukura@gmail.com"
}

###
DELETE http://localhost:7070/kurious/instructor/5efeffcff6e69021ecde08c4
