GET http://localhost:7070/kurious/message
###
GET http://localhost:7070/kurious/message/user/5eff02bcf21877015cd15daf
###
POST http://localhost:7070/kurious/message
Content-Type: application/json

{
    "sender": "5eff02bcf21877015cd15daf",
    "reciever": "5eff02bcf21877015cd15daf",
    "content": "neda oda feda shwi da"
}

###
PUT http://localhost:7070/kurious/message/5f0b9e6265ebec2a5c996bda
Content-Type: application/json

{
    "sender": "5eff02bcf21877015cd15daf",
    "reciever": "5eff02bcf21877015cd15daf",
    "content": "neda oda feda shwi da"
}

###
DELETE http://localhost:7070/kurious/message/5eff0468b634e405cc48bef6
