GET http://localhost:7070/kurious/collegeYear
###
GET http://localhost:7070/kurious/collegeYear/college/5efdd646752e750798e84888
###
GET http://localhost:7070/kurious/collegeYear/5eff0468b634e405cc48bef6
###

POST http://localhost:7070/kurious/collegeYear
Content-Type: application/json

{
    "digit": 3
}


###
DELETE http://localhost:7070/kurious/collegeYear/5f0aa4101aeffd256cb07d91
