GET http://localhost:7070/kurious/facility-college-year
###
POST http://localhost:7070/kurious/facility-college-year
Content-Type: application/json

{
    "facilityCollege": "5f0d31ed352a431c88dc954f",
    "collegeYear": "5f0d321c352a431c88dc9550"
}

###
DELETE http://localhost:7070/kurious/facility-college-year/5f0ab4a77c1ace2c7470e795
