GET http://localhost:7070/kurious/facility-college
###
POST http://localhost:7070/kurious/facility-college
Content-Type: application/json

{
    "facility": "5f0d3159ce1f4d1cbc695100",
    "college": "5efdd646752e750798e84888"
}

###
DELETE http://localhost:7070/kurious/facility-college/5f0a7042db08201ac41b698a
