GET http://localhost:7070/kurious/facility
###
GET http://localhost:7070/kurious/facility/college/5efdd646752e750798e84888
###
GET http://localhost:7070/kurious/facility/5f08dcd874bd6d1b8ce72ea3
###

POST http://localhost:7070/kurious/facility
Content-Type: application/json

{
    "name": "Cival ..."
}

###
PUT http://localhost:7070/kurious/facility/5f08dcd874bd6d1b8ce72ea3
Content-Type: application/json

{
    "name": "Java"
}

###
DELETE http://localhost:7070/kurious/facility/5f08dcd874bd6d1b8ce72ea3
