GET http://localhost:7070/kurious/student
###
GET http://localhost:7070/kurious/student/college/5efdd646752e750798e84888
###
GET http://localhost:7070/kurious/student/5eff0468b634e405cc48bef6
###

POST http://localhost:7070/kurious/student
Content-Type: application/json

{
    "surName": "Nadine",
    "otherNames": "Umukura",
    "nationalId": "1103473948628496",
    "gender": "FeMale",
    "phone": "9999000000",
    "email": "umukura@gmail.com",
    "college": "5efdd646752e750798e84888",
    "DOB": "01-01-2002"
}

###
PUT http://localhost:7070/kurious/student/5eff0468b634e405cc48bef6
Content-Type: application/json

{
    "surName": "Nadina",
    "otherNames": "Umukura",
    "nationalId": "1103473948628496",
    "gender": "FeMale",
    "phone": "9999000000",
    "email": "umukura@gmail.com",
    "college": "5efdd646752e750798e84888"
}

###
POST http://localhost:7070/kurious/student/login
Content-Type: application/json

{
    "password": "Kurious@2020",
    "email": "umukura@gmail.com"
}

###
DELETE http://localhost:7070/kurious/student/5eff0468b634e405cc48bef6
